## Numpy  - vectors and matrices

Let's start with numpy and working with vectors and matrices, at first we 
have a look on numpy arrays and try the matrix-vector-multiplication

In [1]:
import numpy as np

# have a list of values
vl=[1.23,2.23,3.23,4.23]

# and make it to a numpy array
v=np.array([vl])

print(vl,type(vl))
print(v,type(v))
print(v.ndim,v.shape)

# create a matrix
# see the value 1.0 instead of 1
# what is the difference ? 
A=np.array( [[1.0,2,3,4],[5,6,7,8]] )

print(A,type(A))
print(A.ndim,A.shape)



[1.23, 2.23, 3.23, 4.23] <class 'list'>
[[1.23 2.23 3.23 4.23]] <class 'numpy.ndarray'>
2 (1, 4)
[[1. 2. 3. 4.]
 [5. 6. 7. 8.]] <class 'numpy.ndarray'>
2 (2, 4)


In [2]:
print(A[1,1],type(A[1,1]))
#By use of 1.0 isted of 1, all entities type change to float 

6.0 <class 'numpy.float64'>


Now we look at the matrix - vector multiplication, there is a pitfall for numpy-beginners, if you have a matrix A and a vector v and write ```b=A*v``` you get **not** what you want.

In [3]:
# matrix-vector multiplication -- wrong way 
# the * is a simple array multiplication and NOT the matrix-multiplication
b=A*v
print(b,type(b),b.ndim,b.shape)

[[ 1.23  4.46  9.69 16.92]
 [ 6.15 13.38 22.61 33.84]] <class 'numpy.ndarray'> 2 (2, 4)


Next try, instead of ```b=A*v``` we do 
  * make v from a row vector to the correct column vector -- try out what happens if you skip this
  * use ```b=A.dot(u)``` or ```b=A@u``` for the matrix vector product

In [4]:
# matrix-vector multiplication again

# make v from a row vector to a column vector
# x.T gives in numpy the transposed of x
u=v.T
print(u,type(u),u.ndim,u.shape)

b=A.dot(u)
print(b,type(b),b.ndim,b.shape)

#you can also use the @ operator for matrix multiplication
c=A@u
print(c,type(c),c.ndim,c.shape)


[[1.23]
 [2.23]
 [3.23]
 [4.23]] <class 'numpy.ndarray'> 2 (4, 1)
[[32.3 ]
 [75.98]] <class 'numpy.ndarray'> 2 (2, 1)
[[32.3 ]
 [75.98]] <class 'numpy.ndarray'> 2 (2, 1)


## Task

Play around with the next code blocks to understand the element access and data types

In [5]:
# access to elements 
print(A)
print(A[0,0])
print(A[1,2])

# try the next with 1.0 and 1 in the definition of A above 
A=np.array( [[1,2,3,4],[5,6,7,8]] )
print(A)
# what happens ? 
A[1,3]=-3.14
A[0,0]=-1.68
print(A)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
1.0
7.0
[[1 2 3 4]
 [5 6 7 8]]
[[-1  2  3  4]
 [ 5  6  7 -3]]


In [6]:
x=np.array([1,2,3,4])
print(x)
y=np.array([1.0,2,3.0,4.0])
print(y)

x[0]=1.5
y[0]=1.5
y[1]=2.5
print(x)
print(y)



[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]
[1.5 2.5 3.  4. ]


## Task

Write a function mymat(n) which takes a size argument n>0 and returns a regular nxn Matrix

In [7]:
def mymat(n):
    A=np.zeros((n,n))
    for i in range(n):
        A[i,i]=i+1
    # TODO
    return A

In [8]:
print (mymat(3))

[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]


## Task

Now use your function to create for n=3,5,10 and 15 matrices A and right hand sides $$b = A \cdot [1,1, ... 1]^T$$ and find out 
how you can use numpy.linalg.solve for solving linear systems Ax=b. Check if you get the correct solution $$[1,1,...1]^T$$

In [9]:
n=5
A=mymat(n)
# TODO

x = 0 # replace with solution of Ax=b
x=np.linalg.solve(A,np.ones(n))
print(x)

[1.         0.5        0.33333333 0.25       0.2       ]


# Toeplitz and circulant matrices 

We want to create a Toeplitz matrix and also a circulant matrix, both incredibly important in signal processing. 

Toeplitz matrices are constant along the diagonals from left to rigtht, the structure is
$$T=\left[ \begin{matrix} a & b & c & d & e \\ f & a &  b &  c & d  \\ g & f & a &  b &  c \\ h& g & f & a &  b   
 \\ i & h & g & f & a  \end{matrix} \right] $$

As you can see - a Toeplitz matrix is fully defined by setting the first row and the first column.

# Task

Write a function which takes 2 vectors **c** ( the first column )  and **r** (the first row) 
as numpy arrays and returns the Toeplitz matrix, defined by this vectors. 

In [10]:
def toeplitz(c,r):
    if(r[0] != c[0] ):
        raise ValueError('Error c[0] must be equal r[0] but  %f %f ' % (c[0],r[0]))
        
    # TODO
    n=len(c)
    if(len(r)!=n):
        raise ValueError('The lenth of vectors should be equal')
    T=np.zeros((n,n)) 
    
    for i in range(n):
            for j in range(n-i):
                T[j,i+j]=r[i]
                if i>0: T[i+j,j]=c[i]
    return T

In [11]:

r=np.array([1,2,3,4])
c=np.array([1,5,6,7])
T=toeplitz(c,r)
print(T)

[[1. 2. 3. 4.]
 [5. 1. 2. 3.]
 [6. 5. 1. 2.]
 [7. 6. 5. 1.]]



## Circulant matrices 

Circulant matrices are square matrices and fully defined by its first column **c** and have the structure

$$C=\left[ \begin{matrix} 
a & e & d & c & b \\ 
b & a & e & d & c  \\ 
c & b & a & e & d \\ 
d & c & b & a & e    \\ 
e & d & c & b & a  \end{matrix} \right] $$

You can see that Circulant matrices are a special kind of Toeplitz matrices.

## Task

Write a function which takes a vector **c** as 1 numpy array 
and returns the Circulant matrix, defined by this vector. 


In [12]:
def circulant(c):
    # TODO
    n=len(c)
    C=np.zeros((n,n)) 
    for j in range(n):
        for i in range(j,j+n):
            if i<n :
                C[i,j]=c[i-j]
            else:
                C[i%n,j]=c[(i-j)%n]
    return C
    

In [13]:
r=[3,5,7,9]
C=circulant(r)

In [14]:
print(C)


[[3. 9. 7. 5.]
 [5. 3. 9. 7.]
 [7. 5. 3. 9.]
 [9. 7. 5. 3.]]


# Fourier matrix

The Fourier matrix $F$ of size $n \times n$ is defined as
$$
F=\frac{1}{\sqrt{n}}
\left[
\begin{array}
\cdot & \cdot & \cdot \\
\cdot & \omega^{jk} & \cdot \\
\cdot & \cdot & \cdot \\
\end{array}
\right]_{j,k=0}^{n-1}
$$
where $\omega$ is the n-th primitive root of unity, i.e. $$\omega=e^{-2\Pi i / n}$$

## Task

Write a function which computes for given size **n** the Fourier matrix $F$.

(Later we will use scipy - there is the Fouriermatrix given as build in, but now we do it by hand)
  * Hint 1 : The complex number **i** you can get in numpy as **1.j**
  * Hint 2 : $\Pi$ you get as np.pi
  * Hint 3 : in complex computations initialize your data types correct, f.e. 
    ``` F=np.zeros((n,n),dtype=complex) ``` . Try out what happens if you do it as 
    ``` F=np.zeros((n,n)) ```


In [15]:
def fourier(n):
    # create a complex zero matrix
    F=np.zeros((n,n),dtype=complex)
    # TODO
    for j in range(n):
        for k in range(n):
            F[j,k]= (np.exp(-2*j*k*np.pi*1.j/n))
    return F/np.sqrt(n)

In [16]:
F=fourier(4)
print(F)


[[ 5.00000000e-01+0.0000000e+00j  5.00000000e-01+0.0000000e+00j
   5.00000000e-01+0.0000000e+00j  5.00000000e-01+0.0000000e+00j]
 [ 5.00000000e-01+0.0000000e+00j  3.06161700e-17-5.0000000e-01j
  -5.00000000e-01-6.1232340e-17j -9.18485099e-17+5.0000000e-01j]
 [ 5.00000000e-01+0.0000000e+00j -5.00000000e-01-6.1232340e-17j
   5.00000000e-01+1.2246468e-16j -5.00000000e-01-1.8369702e-16j]
 [ 5.00000000e-01+0.0000000e+00j -9.18485099e-17+5.0000000e-01j
  -5.00000000e-01-1.8369702e-16j  2.75545530e-16-5.0000000e-01j]]


## Diagonalization of a circulant matrix

With the help of our Fouriermatrix $F$  we can diagonlize the circulant matrix $C$ with
$$ D = \bar{F}C F $$
where $\bar{F}$ is the complex conjugate matrix of $F$, let's try this out.

In [17]:
# matrix multiplication with the @ operator
D=np.conjugate(F)@C@F
print(D)


[[ 2.40000000e+01+0.00000000e+00j -1.10218212e-15-8.88178420e-16j
   0.00000000e+00-1.46957616e-15j  2.41836794e-15-1.77635684e-15j]
 [-7.77156117e-16+6.66133815e-16j -4.00000000e+00-4.00000000e+00j
   2.22044605e-16+2.67814115e-16j -4.44089210e-16+4.44089210e-16j]
 [ 0.00000000e+00+1.46957616e-15j  4.17184002e-16+1.11022302e-16j
  -4.00000000e+00+0.00000000e+00j -1.60812265e-16+4.44089210e-16j]
 [ 2.44249065e-15+2.22044605e-15j  4.44089210e-16-8.88178420e-16j
   2.77007651e-31+2.67814115e-16j -4.00000000e+00+4.00000000e+00j]]


The result $D$ is not very good readable because of the zeros written as small numbers in range $10^{-16}$. So we do some matrix cosmetic and cut off small numbers

In [18]:
tol=1e-12
D.real[abs(D.real) < tol] = 0.0
D.imag[abs(D.imag) < tol] = 0.0

print(D.real)
#print(D.imag)


[[24.  0.  0.  0.]
 [ 0. -4.  0.  0.]
 [ 0.  0. -4.  0.]
 [ 0.  0.  0. -4.]]



Now $D$ looks like a diagonal matrix :-) 

The construction of $F$ and $C$ can be avoided if the **Fast Fourier Transfor (FFT)** is used and the complexity reduces to something that is $\mathcal{O}(n\mathrm{log}(n))$ rather than $\mathcal{O}(n^2)$

[here](https://math.mit.edu/icg/resources/teaching/18.085-spring2015/toeplitz.pdf) you can find the information of how to embedd a Toeplitz matrix into a circulant matrix. Implement this function and verify with a DFT of the double size that this is diagonalized using $F$.



