# Exercise for Object Orientation

Write the definition of a `Point` class for handling points in the 3-dimensional space $R^3$. 
Objects from this class should have a
* a method `show` to display the coordinates of the point
* a method `move` to move a point 
* a method `dist` that computes the distance between 2 points
* a method `dotprod` that computes the scalar product of 2 points
* a method `crossrod` that computes the scalar product of 2 points
* a method `norm` that returns the norm of the point
* a method `normalize` that makes the points norm equal 1
* a method `scale` that scales the point by scalar alpha 





In [83]:

class Point(object):
    """Class to handle point in R^3"""

    def __init__(self, x, y, z):
        """
        :param x,y,z: coordinates
        :type x,y,z:  float
        """
        self.x = x
        self.y = y
        self.z = z

    def show(self):
        """
        :return: the coordinate of this point
        :rtype: a tuple of 3 elements (float, float,float)
        """
        return self.x, self.y, self.z

    # ... TODO 
    def move(self,p):
        """
        :return: the cordinate of this point moved by p
        """
        m=Point(p.x+self.x , p.y+self.y, p.z+self.z)
        return m

    def norm(self):
        """
        :return:The norm of this point
        """
        return (self.x**2+self.y**2+self.z**2)**0.5
        
    
    
    def scale(self,t):
        """
        :return: 
        """
        tp=Point(t*self.x,t*self.y,t*self.z)
        return tp


    def normalize(self):
        """
        :return: 
        """
        norm=self.norm()
        self.x/=norm
        self.y/=norm
        self.z/=norm

    def crossprod(p,q):
        """
        :return: Cross Product
        """
        pxq = Point(p.y*q.z-p.z*q.y,p.z*q.x-p.x*q.z,p.x*q.y-p.y*q.x)
        return pxq

    def dotprod(p,q):
        """
        :return: Dot product
        """
        return p.x*q.x+p.y*q.y+p.z*q.z

    def dist(p,q):
        """
        :return: Distans of two point in R3
        """
        return ((p.x-q.x)**2+(p.y-q.y)**2+(p.z-q.z)**2)**.5

In [90]:
p1 = Point(1,2,3)
p2 = Point(4,5,6)

print ('p1:', p1.show() )
print ('p2:', p2.show() )
#print(type(p1))

#print(p1.move(p2).show())
print(p1.norm())
p1.normalize()
print(p1.show())
print(p1.norm())
#print(Point.dist(p1,p2))
#print(Point.dotprod(p1,p2))
#print(Point.crossprod(p1,p2).show())
print(type(Point.crossprod(p1,p2)))
#print(Point.crossprod(p1,p1).show())


p1: (1, 2, 3)
p2: (4, 5, 6)
3.7416573867739413
(0.2672612419124244, 0.5345224838248488, 0.8017837257372732)
1.0
1.9639610121239315


Check your Implementation on some simple examples

In [65]:
p1 = Point(1,2,3)
p2 = Point(4,5,6)

print ( p1.show() )
print ( p2.show() )

p1.move(p2)
print ( p1.show() )

print(p1.norm())
p1.normalize()
print(p1.norm())


Point.dotprod(p1,p1)
n=Point.crossprod(p1,p2)
print(n.show())

n=Point.crossprod(p2,p2)
print(n.show())



(1, 2, 3)
(4, 5, 6)
(1, 2, 3)
3.7416573867739413
1.0
(-0.8017837257372729, 1.6035674514745464, -0.8017837257372733)
(0, 0, 0)


(1, 2, 3)
(4, 5, 6)
(1, 2, 3)
6.0
1.0
(-0.5, 1.0, -0.5)
(0, 0, 0)

##  Geometry in $R^3$

Now we want to do some geometry in $R^3$. We define classes for a line and a plane, based on our point class with:

Line:
 * a init method to define the line by starting point x0 and direction vector v
 
Plane: 
 * a init method to define the plane by starting point x0 and direction vectors v,w
 * a normal method to return the normal of the plane (normalized)
 * a line_intersection method which returns the intersection with a given line g 

In [212]:
sp.init_printing()
t,k,l = sp.symbols('t k l')

import numpy as np

class Line(Point):
    """Class to handle lines in R^3"""
    
    def __init__(self, p, v):
        """
        :param p: a point of line
        :param v: direction of line
        :type p,y:  Point class
        """
        self.p=p
        self.v =v
        
    
class Plane(Point): 
    """Class to handle planes in R^3"""
    def __init__(self, p, v , w):
        """
        :param p: a point of line
        :param v,w: direction of line
        :type p,y,w:  Point class
        """
        self.p =p
        self.v =v
        self.w =w
        
    def normal(self):
        vxw=Point.crossprod(self.v,self.w)
        Point.normalize(vxw)
        return vxw
    
    
    def line_intersection(self,g):
        if Point.crossprod(self.normal(),g.v)==0:
            return 'There is no intersection'
        else:
            v=g.v
            P0=g.p
            n=self.normal()
            t0= sp.solve(n.x*(v.x*t+P0.x)+n.y*(v.y*t+P0.y)+n.z*(v.z*t+P0.z))
            t0=t0[0]
            intersection = Point(v.x*t0+P0.x,v.y*t0+P0.y,v.z*t0+P0.z)
            return intersection
        
        
    def plane_intersection(self,E):
        N1=self.normal()
        P1=self.p
        
        N2=E.normal()
        P2=E.p
        
        N=Point.crossprod(N1,N2)

        
        print(N1.show(),N2.show(),N.show(),Point.dotprod(N1,P1),Point.dotprod(N2,P2))
        
        A=np.array([[N1.x,N1.y,N1.z],[N2.x,N2.y,N2.z],[N.x,N.y,N.z]])
        b=np.array([Point.dotprod(N1,P1) ,Point.dotprod(N2,P2),0])
        print(A,b)
        XY=np.linalg.solve(A,b)
        print('XY',XY)
        return 'n'
        
    
    # ... TODO

Do some tests with the Plane and Line class, check the values.

In [216]:
############TEST

# x-y plane
x0=Point(0,0,0)
v =Point(1,0,0)
w =Point(0,1,0)
E =Plane(x0,v,w) 

# x-z plane
x0=Point(0,0,0)
v =Point(1,0,0)
w =Point(0,0,1)
E2 =Plane(x0,v,w) 

# should be the x-axis 
E.plane_intersection(E2)
#print(r.x0.show())
#print(r.v.show())

(0.0, 0.0, 1.0) (0.0, -1.0, 0.0) (1.0, 0.0, -0.0) 0.0 0.0
[[ 0.  0.  1.]
 [ 0. -1.  0.]
 [ 1.  0. -0.]] [0. 0. 0.]
XY [ 0. -0.  0.]


'n'

In [152]:
P0=Point(1,1,1)
v =Point(1,2,1)
g=Line(P0,v)

P1=Point(1,2,3)
v =Point(4,5,6)
w =Point(7,8,9)
E =Plane(P1,v,w) 

n=E.normal()
print (n.show())


(-0.408248290463863, 0.816496580927726, -0.408248290463863)


### Intersection plane-line
Now go ahead to our Plane class and implement a method

* line_intersection(self,g)

which returns the intersection point of the plane with line g. Then check it with the following calls:

In [153]:
s=E.line_intersection(g)
print(s.show())

(1.00000000000000, 1, 1.00000000000000)


In [159]:
s=E.line_intersection(g)
print(s.show())

[[ 1. -4. -7.]
 [ 2. -5. -8.]
 [ 1. -6. -9.]]
6.000000000000005
(1.0, 1.0, 1.0)


### Intersection plane - plane
Now again go ahead to our Plane class and implement a method

    plane_intersection(self,E)

which returns the intersection line of the plane with another plane E. 

This can be done by having the planes in normal form:
$$
E_1: n_1 \cdot x + d_1=0 \\
E_2: n_2 \cdot x + d_2=0 \\
$$
where $\cdot$ is the scalar product and $n_1$,$n_2$ the normal vectors of the planes.

So we have $2$ equations for $3$ unknowns $x_1,x_2,x_3$. 

Lets add the condition:
$$
(n_1 \times n_2) \cdot x = 0
$$
with $\times$ as the cross product in R^3, which leads to $3$ equations for $3$ unknowns.

The solution $x$ is a point on the intersection line, because it fulfills both plane equations.

Moreover $(n_1 \times n_2)$ is a vector whicht is orthogonal to both  normal vectors of the planes,
so it is parallel to both planes and a direction vector of the intersection line.


Then check it with the following calls:


0.0 0 0.0 0
[0.05882353 0.11764706]


'n'

In [160]:
# x-y plane
x0=Point(0,0,0)
v =Point(1,0,0)
w =Point(0,1,0)
E =Plane(x0,v,w) 

# x-z plane
x0=Point(0,0,0)
v =Point(1,0,0)
w =Point(0,0,1)
E2 =Plane(x0,v,w) 

# should be the x-axis 
r=E.plane_intersection(E2)
print(r.x0.show())
print(r.v.show())



[[ 0.  0.  1.]
 [ 0. -1.  0.]
 [ 1. -0. -0.]]
1.0
(0.0, -0.0, 0.0)
(1.0, -0.0, -0.0)


As the last task for today compute the intersection line of the planes:
$$
E1: \quad  \left[ \begin{matrix}  x \\  y \\ z \end{matrix} \right]
=          \left[ \begin{matrix}  1 \\  4 \\ 3  \end{matrix} \right]
+ \lambda_1  \left[ \begin{matrix}  0 \\  2 \\ 1  \end{matrix} \right]
+ \eta_1     \left[ \begin{matrix} -1 \\  4 \\ 0  \end{matrix} \right]
$$


$$
E2: \quad  \left[ \begin{matrix}  x \\  y \\ z \end{matrix} \right]
=          \left[ \begin{matrix}  6 \\  4 \\ 2  \end{matrix} \right]
+ \lambda_2  \left[ \begin{matrix}  3 \\  3 \\ 2  \end{matrix} \right]
+ \eta_2     \left[ \begin{matrix}  2 \\  1 \\ -1  \end{matrix} \right]
$$

Because one can use different starting points and different scaled direction vectors for a line your
solution will not have the same numbers like the solution 

$$
g: \quad  \left[ \begin{matrix}  x \\  y \\ z \end{matrix} \right]
=         \left[ \begin{matrix}  1 \\  0 \\ 1  \end{matrix} \right]
+  t      \left[ \begin{matrix}  1 \\  2 \\ 3  \end{matrix} \right]
$$

Implement a test which say if your solution is the line g from above or not.

In [161]:
x0=Point(1,4,3)
v =Point(0,2,1)
w =Point(-1,4,0)
E1 =Plane(x0,v,w) 

x0=Point(6,4,2)
v =Point(3,3,2)
w =Point(2,1,-1)
E2 =Plane(x0,v,w) 

r=E1.plane_intersection(E2)
print(r.x0.show())
print(r.v.show())

def samelines(g1,g2):
    
    # TODO
    
    if ( ... ):
        print("  ... looks good ")
    else:
        print("  ... looks bad ")
    
    
    

x0=Point(1,0,1)
v=Point(1,2,3)
gs=Line(x0,v)

samelines(gs,r)




[[-0.87287156 -0.21821789  0.43643578]
 [-0.5488213   0.76834982 -0.32929278]
 [-0.26347778 -0.52695556 -0.79043333]]
0.971887550200803
(0.7142857142857145, -0.571428571428572, 0.14285714285714315)
(-0.26347777762091695, -0.5269555552418339, -0.7904333328627509)
||d||=0.000000 ... looks good 
