In [2]:
import numpy as np
A = np.matrix([[2 , 1], [5 , 7]])
b=np.array([11,13])
b
A

matrix([[2, 1],
        [5, 7]])

In [11]:
D=A.diagonal()
L=np.tril(A)

In [11]:
U=np.triu(A)

In [11]:
L

array([[3, 0, 0],
       [6, 4, 0],
       [1, 3, 5]])

In [11]:
D=A.diagonal()
L=np.tril(A)

In [11]:
U=np.triu(A)

In [11]:
L

array([[3, 0, 0],
       [6, 4, 0],
       [1, 3, 5]])

In [20]:
LI=np.linalg.inv(L)
LI

array([[ 3.33333333e-01,  3.70074342e-17, -2.37904934e-17],
       [-5.00000000e-01,  2.50000000e-01,  3.56857401e-17],
       [ 2.33333333e-01, -1.50000000e-01,  2.00000000e-01]])

In [26]:


import scipy.sparse as sp

T=L@LI
sp.issparse(L)

False

In [4]:
from numpy.linalg import inv

Linv = inv(L)

Linv

array([[ 5.00000000e-01,  1.11022302e-17],
       [-3.57142857e-01,  1.42857143e-01]])

In [5]:
np.diag(1 / np.diag(D))

array([[0.5]])

In [6]:
S=np.array([[ 0, 0, 0],
[ 4, 0, 0],
[ 7, 8, 0],
[10, 11, 12]])

In [7]:
np.triu(S)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [8]:
def jacobi(A,b,maxiter,tol,verbose,xInit):
    xOld=xInit
    D = np.diag(np.diag(A))
    LU = A - D
    for i in range(maxiter):
        DInv = np.diag(1 / np.diag(D))
        xNew = np.dot(DInv, b - np.dot(LU, xOld))
        if np.linalg.norm(xNew - xOld) < tol:
            if verbose==1:
                print(f'number of iteration:{i}')
            return (xNew ,i)
        xOld = xNew    

In [9]:
A = np.array([
    [3, 5, 1],
    [6, 4, 2],
    [1, 3, 5]
])
b = np.array([12, 5, 20])

A4 = np.array([
    [5, 2, 1, 1],
    [2, 6, 2, 1],
    [1, 2, 7, 1],
    [1, 1, 2, 8]
])
b4 = np.array([29, 31, 26, 19])


x0 = np.zeros(len(b))

(x ,i)= jacobi(A, b,1000,1e-5,1,x0)
print('x=' , x)
print("b'=", np.dot(A, x))

TypeError: cannot unpack non-iterable NoneType object

In [19]:
from scipy import linalg
a = np.array([[1., 2.], [3., 4.]])
linalg.inv(a)


np.dot(a, linalg.inv(a))


array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [5]:
a = np.array([1., 2.,4.])
a[0]+3

4.0

In [7]:
p=(2,3,4)
type(p)

tuple

In [8]:
p[1]

3

In [9]:
np.sqrt(2)

1.4142135623730951

In [24]:
(2**0.5)


In [13]:
import math 
math.sqrt(2)

1.4142135623730951

In [20]:
import sympy as sp
sp.init_printing()

sp.sqrt(3.5)

In [25]:
import numpy as np
np.sqrt(2)

In [52]:
sp.init_printing()
X,Y,Z = sp.symbols('X Y Z')

import numpy as np

class Line(Point):
    """Class to handle lines in R^3"""
    
    # ... TODO
    def __init__(self, p, v):
        """
        :param p: a point of line
        :param v: direction of line
        :type p,y:  Point class
        """
        self.p=p
        self.v =v
    #def direction(self):
        
        
    
class Plane(Point): 
    """Class to handle planes in R^3"""
    def __init__(self, p, v , w):
        """
        :param p: a point of line
        :param v,w: direction of line
        :type p,y,w:  Point class
        """
        self.p =p
        self.v =v
        self.w =w
        #self.n=n
        
    def normal(self):
        vxw=Point.crossprod(self.v,self.w)
        #print(type(vxw))
        Point.normalize(vxw)
        #print(vxw.show(),type(vxw))
        self.n=vxw
        return vxw
    
    
    def line_intersection(self,g):
        if Point.crossprod(self.normal(),g.v)==0:
            return 'There is no intersection'
        else:
            v=g.v
            P0=g.p
            n=self.normal()
            t0= sp.solve(n.x*(v.x*t+P0.x)+n.y*(v.y*t+P0.y)+n.z*(v.z*t+P0.z))
            t0=t0[0]
            intersection = Point(v.x*t0+P0.x,v.y*t0+P0.y,v.z*t0+P0.z)
            return intersection
        
        
    def plane_intersection(self,E):
        N1=self.normal()
        P1=self.p
        
        N2=E.normal()
        P2=E.p
        
        N=Point.crossprod(N1,N2)

        
        #eq1=N1.x*(k-P1.x)+N1.y*(l-P1.y)
        #eq2=N2.x*(k-P2.x)+N2.y*(l-P2.y)
        
        #np.solve([eq1,eq2],[k,l])
        #print(N1.show(),N2.show())
        print(N1.show(),N2.show(),N.show(),Point.dotprod(N1,P1))
        A=np.array([[N1.x,N1.y,N1.z],[N2.x,N2.y,N2.z],[N.x,N.y,N.z]])
        b=np.array([Point.dotprod(N1,P1) ,Point.dotprod(N2,P2),0])
        print(A,b)
        XY=np.linalg.solve(A,b)
        print('XY',XY)
        return 'n'
        
    
    # ... TODO

In [53]:
# x-y plane
x0=Point(0,0,0)
v =Point(1,0,0)
w =Point(0,1,0)
E =Plane(x0,v,w) 

# x-z plane
x0=Point(0,0,0)
v =Point(1,0,0)
w =Point(0,0,1)
E2 =Plane(x0,v,w) 

E.plane_intersection(E2)

(0.0, 0.0, 1.0) (0.0, -1.0, 0.0) (1.0, 0.0, -0.0) 0.0
[[ 0.  0.  1.]
 [ 0. -1.  0.]
 [ 1.  0. -0.]] [0. 0. 0.]
XY [ 0. -0.  0.]


'n'

In [46]:
p1 = Point(1,2,3)
p2 = Point(4,5,6)

print ('p1:', p1.show() )
print ('p2:', p2.show() )
#print(type(p1))

#print(p1.move(p2).show())
print(p1.norm())
Point.normalize(p1)
print(p1.show())
print(p1.norm())
#print(Point.dist(p1,p2))
#print(Point.dotprod(p1,p2))
#print(Point.crossprod(p1,p2).show())
print(type(Point.crossprod(p1,p2)))
#print(Point.crossprod(p1,p1).show())


p1: (1, 2, 3)
p2: (4, 5, 6)
3.7416573867739413
(0.2672612419124244, 0.5345224838248488, 0.8017837257372732)
1.0
<class '__main__.Point'>


In [29]:
import numpy as np
A=np.array([[2,3],[4,5]])
b=np.array([1,1])
x=np.linalg.solve(A,b)
print(x)

[-1.  1.]
